### ISSUE TITLE
how did you create the .deb files ?

### ISSUE THREAD

**Issue by andres0820m** [kecsap/tensorflow_cpp_packaging#16]
This is not a issue but can u explany me how did you create the .deb files ?? and planing to to the same but for tf 2.0

**Comment by kecsap** [comment]
I have bad news. The last version, which works, is TF 1.13.1, even 1.14 does not work because they deprecated the old graph freezing approach to deploy models and as I could see 1-2 months ago, the new APIs were still unstable in 2.0 for model deployment.
Probably, this whole project will be stuck at TF 1.13.1 and community has to find a working approach to deploy TF 2.0 models with C++ API.
