### ISSUE TITLE
2_make_wheel_for_headers.sh and ./3_build_tensorflow_cpp_optimized_x86_64.sh execution with fail

### ISSUE THREAD

**Issue by Haffon** [kecsap/tensorflow_cpp_packaging#4]
- The first issue is 2_make_wheel_for_headers.sh need install bazel, why not provide the header files for the beginner?

- The second issue is 3_build_tensorflow_cpp_optimized_x86_64.sh need some fix, 1>need remove uncomment line 27 and 28 to execute cmake for the first time to compile. 2>need set tensorflow_ENABLE_GRPC_SUPPORT to ON as double_conversion depends on gRPC if you compile tensorflow 1.10.0(the last release is 1.10.1).

**Comment by kecsap** [comment]
Bazel: I added instruction to the README to install Bazel now. Header files can't be provided because if they are changed in Tensorflow and you build against the wrong headers, your app will crash and you will scratch your head for a week what the heck is the problem. This is specific to C/C++.

Script: Oops, I forgot some comments there. Did you notice that some line above are also commented which should not be. E.g. some patches are applied which fix some compilation issues, including tensorflow_ENABLE_GRPC_SUPPORT.

I pushed fixes. Please try again and let me know if there are still other issues.

**Comment by Haffon** [comment]
The header files should be stable in product environment, but state of the art library is update so fast, we deploy tensorflow 1.8.0 in some days, it is 1.10.1 now when we want to study new model. Hard to catch up.

I stopped at ENABLE_GRPC_SUPPORT option, and don't notice other issues. It is obviously you know better than me.

**Comment by kecsap** [comment]
Yeap. My scripts were also only tested on x86_64 Ubuntu 18.04 with Tensorflow 1.10.0. It is impossible to provide a generic solution for this packaging problem because Tensorflow changes so quickly. My github project is like a guidance beyond the supported/fixed scenarios.
