### ISSUE TITLE
error: tensorflow/c/c_api.cc: patch does not apply

### ISSUE THREAD

**Issue by laithehoangbk** [kecsap/tensorflow_cpp_packaging#7]
I run _./3_build_tensorflow_cpp_arm_rpi.sh_
but i get
_Checking out files: 100% (11415/11415), done.
HEAD is now at 25c197e023 Merge pull request #20455 from lygztq/r1.9
warning: tensorflow/contrib/makefile/build_all_linux.sh has type 100755, expected 100644
error: patch failed: tensorflow/c/c_api.cc:2396
error: tensorflow/c/c_api.cc: patch does not apply_
How fix it?

Thank you

**Comment by kecsap** [comment]
Currently, these patches were not updated since Tensorflow 1.10. If you want to compile yourself without hassle, check out the git version 56e4ea405d of the Tensorflow repo.

**Comment by laithehoangbk** [comment]
Hi @kecsap,
Thank you for your prompt reply. I will wait for the update.

**Comment by kecsap** [comment]
I don't think you can get too much benefits from Tensorflow 1.12 compared to 1.10 on Raspberry Pi since there is no deep learning acceleration on that system. If you don't require some very specific new functionality, you can compile 1.10. If you have Ubuntu Mate or similar Debian system, you can try the release package without compilation:
https://github.com/kecsap/tensorflow_cpp_packaging/releases/download/Tensorflow_1.10.0fix1_git20180810_56e4ea40/tensorflow-cpp-rpi_1.10.0.git20180810.56e4ea4.ppa1_armhf.deb

**Comment by laithehoangbk** [comment]
Hi @kecsap,
Thank you
I want a libtensorflow_cc.so for armv7l. Can you build for me?
I was try to build by myself, but having many issue. I have ask for help but no one can help me to resolve that issue.
If you are working with armv7l like me. Please share me the libtensorflow_cc v1.10.0 armv7l

Thank you very much, hope to hear from you soon.

**Comment by kecsap** [comment]
I can't build that, I doubt if it is even supported at all from Tensorflow side.

**Comment by laithehoangbk** [comment]
Thank you very much

**Comment by hhojatansari** [comment]
I got same error on RPi 3B (Ubuntu 18 Mate, Tensorflow 1.7)

**Comment by kecsap** [comment]
@hhojatansari The latest git version was not tested on RPi/Ubuntu 18 Mate. You can try to build this git version ed108c42 to compile Tensorflow 1.10, but nothing guarantees that it will built on Ubuntu 18.04 Mate. I will try to find some time this week to upgrade my RaspPi and do a new build.
